//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountManagment
    {
        public long SystemId { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
        public int Acc_No { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<long> branchId { get; set; }
        public int currencyId { get; set; }
        public long TreeID { get; set; }
        public string AccType { get; set; }
        public decimal Balance { get; set; }
        public string TranAmt { get; set; }
        public string Type { get; set; }
        public long CustomerId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Tree Tree { get; set; }
    }
}
