//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Items = new HashSet<Item>();
        }
    
        public int Comp_ID { get; set; }
        public Nullable<int> Comp_Type_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Name_AR { get; set; }
        public string Logo { get; set; }
        public Nullable<int> Activity_ID { get; set; }
        public string Commercial_No { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Curr_ID { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual City City { get; set; }
        public virtual Company_Type Company_Type { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
