//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyActivity()
        {
            this.Exps = new HashSet<Exp>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> OpenningBal { get; set; }
        public Nullable<decimal> paymentAmount { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> SoldAmount { get; set; }
        public Nullable<decimal> RemainedAmt { get; set; }
        public string Entered_By { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> DayDate { get; set; }
        public string OpenStatus { get; set; }
        public string cashierID { get; set; }
        public string ExpensesDesc { get; set; }
        public int Branch_ID { get; set; }
        public int Warehouse_ID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exp> Exps { get; set; }
    }
}
