//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Loans
    {
        public int loan_id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<long> acc_no { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Entered_By { get; set; }
    
        public virtual Employess Employess { get; set; }
        public virtual Tree Tree { get; set; }
    }
}
