//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employess()
        {
            this.WareHouses = new HashSet<WareHouse>();
            this.Emp_Loans = new HashSet<Emp_Loans>();
            this.Ride = new HashSet<Ride>();
        }
    
        public int Emp_ID { get; set; }
        public string Name { get; set; }
        public string Name_AR { get; set; }
        public string Job_Tittle { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<System.DateTime> Expdate_IQAMA { get; set; }
        public Nullable<System.DateTime> Expdate_Pass { get; set; }
        public string Passport_Id { get; set; }
        public string IQAMA { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareHouse> WareHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Loans> Emp_Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ride> Ride { get; set; }
    }
}
