//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp
    {
        public int Expid { get; set; }
        public string Naration { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Warehouse_ID { get; set; }
        public Nullable<int> dailyID { get; set; }
        public string Entered_By { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual DailyActivity DailyActivity { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
