//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Items
    {
        public int In_Item_ID { get; set; }
        public int Invoice_ID { get; set; }
        public int Item_ID { get; set; }
        public decimal Quantity { get; set; }
        public decimal unit_Price { get; set; }
        public decimal total_Price { get; set; }
        public Nullable<System.DateTime> last_Updated { get; set; }
        public string Status { get; set; }
        public string Entered_By { get; set; }
        public string Approved_By { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public string Item_NameAr { get; set; }
        public string comment { get; set; }
        public Nullable<int> WareHouse_ID { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
