//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PayID { get; set; }
        public Nullable<decimal> currntamount { get; set; }
        public Nullable<System.DateTime> paiddate { get; set; }
        public Nullable<int> currntinst { get; set; }
        public Nullable<int> Cus_ID { get; set; }
        public Nullable<int> Inst_ID { get; set; }
        public string comment { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public string Enterd_By { get; set; }
        public int Warehouse_ID { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Installment Installment { get; set; }
    }
}
