//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Product_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Income_Acc { get; set; }
        public Nullable<int> Expenses_Acc { get; set; }
        public string Name { get; set; }
        public string Name_AR { get; set; }
        public string BAR_CODE { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
        public Nullable<int> Item_Grp_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual Items_Group Items_Group { get; set; }
    }
}
