//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int Supp_ID { get; set; }
        public string Supp_Name { get; set; }
        public string Supp_Name_AR { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string E_Mail { get; set; }
        public string Web_Site { get; set; }
        public string Representative_Name { get; set; }
        public string Representative_Phone { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Entered_By { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string acc_no { get; set; }
        public string Tax { get; set; }
    
        public virtual Country Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
